# SPDX-FileCopyrightText: (C) 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
#
# SPDX-License-Identifier: MulanPSL-2.0

%global crate_name lalrpop-util
%global full_version 0.20.2
%global pkgname lalrpop-util-0.20

Name:           rust-lalrpop-util-0.20
Version:        0.20.2
Release:        %autorelease
Summary:        Rust crate "lalrpop-util"
License:        Apache-2.0 OR MIT
URL:            https://github.com/lalrpop/lalrpop
#!RemoteAsset:  sha256:507460a910eb7b32ee961886ff48539633b788a36b65692b95f225b844c82553
Source:         https://static.crates.io/crates/%{crate_name}/%{full_version}/download#/%{name}-%{version}.tar.gz
BuildArch:      noarch
BuildSystem:    rustcrates

BuildRequires:  rust-rpm-macros

Provides:       crate(%{pkgname}) = %{version}
Provides:       crate(%{pkgname}/std) = %{version}

%description
Source code for takopackized Rust crate "lalrpop-util"

%package     -n %{name}+default
Summary:        Runtime library for parsers generated by LALRPOP - feature "default"
Requires:       crate(%{pkgname}) = %{version}
Requires:       crate(%{pkgname}/std) = %{version}
Requires:       crate(%{pkgname}/unicode) = %{version}
Provides:       crate(%{pkgname}/default) = %{version}

%description -n %{name}+default
This metapackage enables feature "default" for the Rust lalrpop-util crate, by pulling in any additional dependencies needed by that feature.

%package     -n %{name}+lexer
Summary:        Runtime library for parsers generated by LALRPOP - feature "lexer"
Requires:       crate(%{pkgname}) = %{version}
Requires:       crate(%{pkgname}/std) = %{version}
Requires:       crate(regex-automata-0.4/hybrid) >= 0.4.0
Requires:       crate(regex-automata-0.4/perf) >= 0.4.0
Requires:       crate(regex-automata-0.4/std) >= 0.4.0
Requires:       crate(regex-automata-0.4/syntax) >= 0.4.0
Provides:       crate(%{pkgname}/lexer) = %{version}

%description -n %{name}+lexer
This metapackage enables feature "lexer" for the Rust lalrpop-util crate, by pulling in any additional dependencies needed by that feature.

%package     -n %{name}+regex-automata
Summary:        Runtime library for parsers generated by LALRPOP - feature "regex-automata"
Requires:       crate(%{pkgname}) = %{version}
Requires:       crate(regex-automata-0.4/hybrid) >= 0.4.0
Requires:       crate(regex-automata-0.4/perf) >= 0.4.0
Requires:       crate(regex-automata-0.4/syntax) >= 0.4.0
Provides:       crate(%{pkgname}/regex-automata) = %{version}

%description -n %{name}+regex-automata
This metapackage enables feature "regex-automata" for the Rust lalrpop-util crate, by pulling in any additional dependencies needed by that feature.

%package     -n %{name}+unicode
Summary:        Runtime library for parsers generated by LALRPOP - feature "unicode"
Requires:       crate(%{pkgname}) = %{version}
Requires:       crate(regex-automata-0.4/hybrid) >= 0.4.0
Requires:       crate(regex-automata-0.4/perf) >= 0.4.0
Requires:       crate(regex-automata-0.4/syntax) >= 0.4.0
Requires:       crate(regex-automata-0.4/unicode) >= 0.4.0
Provides:       crate(%{pkgname}/unicode) = %{version}

%description -n %{name}+unicode
This metapackage enables feature "unicode" for the Rust lalrpop-util crate, by pulling in any additional dependencies needed by that feature.

%files
%{_datadir}/cargo/registry/%{crate_name}-%{version}/

%changelog
%autochangelog
